controller_frequency: 7.0
recovery_behavior_enabled: true
conservative_reset_dist: 0.2

NavfnROS:
  allow_unknown: true # Specifies whether or not to allow navfn to create plans that traverse unknown space.
  default_tolerance: 0.1 # A tolerance on the goal point for the planner.

TrajectoryPlannerROS:
  # Limits
  acc_lim_x: 8.0
  acc_lim_y: 0.0
  acc_lim_theta: 1.4

  max_vel_x: 2
  min_vel_x: -2

  max_vel_theta: 2
  min_vel_theta: -2

  min_in_place_vel_theta: 0.4
  escape_vel: -0.5

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.3
  latch_xy_goal_tolerance: false

  # differential robot is non-holonomic
  holonomic_robot: false

  # Forward simulation
  sim_time: 2.8
  sim_granularity: 0.025
  # angular_sim_granularity: "sim_granularity"
  vx_samples: 10
  vtheta_samples: 20
  controller_frequency: 20.0 

  #Trajectory scoring parameters
  meter_scoring: false #Whether the gdist_scale and pdist_scale parameters should assume that goal_distance and path_distance are expressed in units of meters or cells. Cells are assumed by default. New in navigation 1.3.1 
  pdist_scale: 0.6    #The weighting for how much the controller should stay close to the path it was given, maximal possible value is 5.0 
  gdist_scale: 0.8    #The weighting for how much the controller should attempt to reach its local goal, also controls speed, maximal possible value is 5.0 
  occdist_scale: 0.01 #The weighting for how much the controller should attempt to avoid obstacles 
  heading_lookahead: 0.8 #How far to look ahead in meters when scoring different in-place-rotation trajectories 
  heading_scoring: false #Whether to score based on the robot's heading to the path or its distance from the path 
  heading_scoring_timestep: 0.8 #How far to look ahead in time in seconds along the simulated trajectory when using heading scoring 
  dwa: true #Whether to use the Dynamic Window Approach (DWA)_ or whether to use Trajectory Rollout (NOTE: In our experience DWA worked as well as Trajectory Rollout and is computationally less expensive. It is possible that robots with extremely poor acceleration limits could gain from running Trajectory Rollout, but we recommend trying DWA first.) 
  publish_cost_grid_pc: true #Whether or not to publish the cost grid that the planner will use when planning. When true, a sensor_msgs/PointCloud2 will be available on the ~<name>/cost_cloud topic. Each point cloud represents the cost grid and has a field for each individual scoring function component as well as the overall cost for each cell, taking the scoring parameters into account. New in navigation 1.4.0 
  global_frame_id: odom


# # 2. If using Dynamic Window Approach
# DWAPlannerROS:
#   # Robot configuration parameters  
#   acc_lim_x: 8.0
#   acc_lim_y: 0.0
#   acc_lim_th: 1.4

#   max_vel_x: 2
#   min_vel_x: -2
#   max_vel_y: 2
#   min_vel_y: -2

#   max_vel_trans: 2
#   min_vel_trans: -2
#   max_vel_theta: 2
#   min_vel_theta: -2

#   # Goal Tolerance Parameters
#   yaw_goal_tolerance: 0.2
#   xy_goal_tolerance: 0.3
#   latch_xy_goal_tolerance: false

#   # # Forward Simulation Parameters
#   sim_time: 2.0
#   # sim_granularity: 0.02
#   vx_samples: 6
#   vy_samples: 0
#   # vtheta_samples: 20
#   # penalize_negative_x: true

#   # # Trajectory scoring parameters
#   # path_distance_bias: 32.0 # The weighting for how much the controller should stay close to the path it was given
#   goal_distance_bias: 24.0 # The weighting for how much the controller should attempt to reach its local goal, also controls speed
#   occdist_scale: 100 # The weighting for how much the controller should attempt to avoid obstacles
#   # forward_point_distance: 0.325 # The distance from the center point of the robot to place an additional scoring point, in meters
#   # stop_time_buffer: 0.2  # The amount of time that the robot must stThe absolute value of the veolicty at which to start scaling the robot's footprint, in m/sop before a collision in order for a trajectory to be considered valid in seconds
#   scaling_speed: 1.0 # The absolute value of the veolicty at which to start scaling the robot's footprint, in m/s
#   # max_scaling_factor: 0.2 # The maximum factor to scale the robot's footprint by

#   # # Oscillation Prevention Parameters
#   oscillation_reset_dist: 0.05 #How far the robot must travel in meters before oscillation flags are reset (double, default: 0.05)

