
obstacle_range: 5.5
raytrace_range: 6.0

resolution: 0.05
robot_radius: 0.1  # Set this to half the width of your robot (35cm wide, so 0.175m)
# footprint: [[-0.075, 0.17], [0.01, 0.17], [0.067, 0.16], [0.117, 0.126], [0.145, 0.08],[0.145, -0.08], [0.117, -0.126],[0.067, -0.16], [0.01, -0.17], [-0.075, -0.17]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 5.0
publish_frequency: 0.5
transform_tolerance: 0.5
