
obstacle_range: 3.0
raytrace_range: 3.5

resolution: 0.05

footprint: [[-0.075, 0.17], [0.01, 0.17], [0.067, 0.16], [0.117, 0.126], [0.145, 0.08],[0.145, -0.08], [0.117, -0.126],[0.067, -0.16], [0.01, -0.17], [-0.075, -0.17]]
# robot_radius: 0.1
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 5.0
publish_frequency: 0.5
transform_tolerance: 0.5
