
obstacle_range: 5.5
raytrace_range: 6.0

resolution: 0.05

footprint: [[-0.075, 0.17], [0.01, 0.17], [0.067, 0.16], [0.117, 0.126], [0.145, 0.08],[0.145, -0.08], [0.117, -0.126],[0.067, -0.16], [0.01, -0.17], [-0.075, -0.17]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 0.5
publish_frequency: 0.5
transform_tolerance: 0.5

static:
    map_topic: map
    subscribe_to_updates: true

# observation_sources: lidar
obstacles_layer:
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true, inf_is_valid: true}

inflation_global:
    inflation_radius: 0.1

inflation_local:
    inflation_radius: 0.1