
base_global_planner: "rrt_star_global_planner/RRTStarPlanner"

global_costmap:
  global_frame: "map"
  robot_base_frame: "base_link"
  static_map: true
  update_frequency: 2.0
  rolling_window: false
  track_unknown_space: false
  resolution: 0.05
  cost_scaling_factor: 3.0

plugins:
  - {name: static_layer,      type: "costmap_2d::StaticLayer"}
  - {name: inflation_global, type: "costmap_2d::InflationLayer"}   
  # - {name: obstacles_global,        type: "costmap_2d::VoxelLayer"}

static_layer:
  map_topic: "/map"
  subscribe_to_updates: true

# obstacles_global:
#   observation_sources: scan
#   scan: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: false}
#   obstacle_range: 10.0

inflation_global:
  inflation_radius: 0.4
