

global_frame: odom
robot_base_frame: base_link
update_frequency: 20.0
publish_frequency: 2.0 # for visualization


rolling_window: true
resolution: 0.05
width: 2
height: 2
origin_x: 0.0
origin_y: 0.0
cost_scaling_factor: 4.0

plugins:
  - {name: inflation_local, type: "costmap_2d::InflationLayer"}
  - {name: obstacles_layer,           type: "costmap_2d::ObstacleLayer"}

observation_sources: lidar
obstacles_layer:
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: false, inf_is_valid: true}
  obstacle_range: 3.0

inflation_local:
  inflation_radius: 0.2
  # cost_scaling_factor: 3.0