

RRTStarPlanner:
  # rrt star parameters
  goal_tolerance: 0.15
  rewiring_radius: 0.4
  epsilon: 0.1
  max_num_nodes: 10000
  # WOA Parameters
  sampling_radius: 0.15
  max_iterations: 1800
  num_agents: 8
  spiral_shape: 0.9


  