

RRTStarPlanner:
  # rrt star parameters
  goal_tolerance: 0.15
  radius: 0.6
  epsilon: 0.2
  max_num_nodes: 10000
  min_num_nodes: 1000
  # WOA Parameters
  sampling_radius: 0.1
  max_iterations: 500
  num_agents: 10
  spiral_shape: 0.8