

RRTStarPlanner:
  # rrt star parameters
  goal_tolerance: 0.2
  radius: 0.3
  epsilon: 0.12
  max_num_nodes: 10000
  # WOA Parameters
  sampling_radius: 0.3
  max_iterations: 2500
  num_agents: 10
  spiral_shape: 0.8