

RRTStarPlanner:
  # rrt star parameters
  goal_tolerance: 0.15
  rewiring_radius: 0.4
  epsilon: 0.1
  max_num_nodes: 10000
  # WOA Parameters
  sampling_radius: 0.18
  max_iterations: 500
  num_agents: 10
  spiral_shape: 0.7


  