# Based on https://github.com/ros-industrial/industrial_ci

name: CI

on: pull_request

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          # - {ROS_DISTRO: melodic, ROS_REPO: testing}
          - {ROS_DISTRO: melodic, ROS_REPO: main}
          # - {ROS_DISTRO: noetic, ROS_REPO: testing}
          # - {ROS_DISTRO: noetic, ROS_REPO: main} # sudo cp *.a /usr/lib
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Configure ROS for install
        run: |
          sudo apt-get install libgtest-dev
          sudo apt-get install cmake # install cmake
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp ./lib/x86_64-linux-gnu/libgtest.a /usr/lib
          sudo cp ./lib/x86_64-linux-gnu/libgtest_main.a /usr/lib
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}