name: build
on: pull_request
jobs:
  build_and_test:
    name: build_and_test
    runs-on: [self-hosted, linux, x64, default]
    strategy:
      fail-fast: false
      matrix:
          distro: [bionic, focal]
    steps:
      - uses: actions/checkout@v2
        id: action_ros_ci_step
      - uses: 'ros-industrial/industrial_ci@master'
        if: failure()
        with:
          distro: ${{ matrix.distro }}
