name: CI

on: pull_request

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: noetic, ROS_REPO: testing}
          - {ROS_DISTRO: noetic, ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}

# name: build
# on: pull_request
# jobs:
#   build_and_test:
#     name: build_and_test
#     runs-on: [self-hosted, linux, x64, default]
#     strategy:
#       fail-fast: false
#       matrix:
#         env:
#           - {ROS_DISTRO: melodic, ROS_REPO: testing}
#           - {ROS_DISTRO: melodic, ROS_REPO: main}
#     steps:
#       - uses: actions/checkout@v2
#         id: action_ros_ci_step
#       - uses: 'ros-industrial/industrial_ci@master'
#         if: failure()
#         with:
#           distro: ${{ matrix.distro }}
